# Generated by Django 4.1.3 on 2022-12-01 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Music', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collaborative_music',
            name='user_id',
            field=models.IntegerField(),
        ),
    ]
