# Generated by Django 4.1.3 on 2022-12-01 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Music', '0003_alter_collaborative_music_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collaborative_music',
            name='rating',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='collaborative_music',
            name='user_id',
            field=models.PositiveIntegerField(),
        ),
    ]
