# Generated by Django 4.1.3 on 2022-12-01 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Music', '0005_alter_collaborative_music_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='collaborative_music',
            name='song_id',
            field=models.IntegerField(default=123),
            preserve_default=False,
        ),
    ]
