# Generated by Django 4.1.3 on 2022-12-01 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Music', '0006_collaborative_music_song_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collaborative_music',
            name='rating',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='collaborative_music',
            name='song_id',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='collaborative_music',
            name='user_id',
            field=models.CharField(max_length=50),
        ),
    ]
