# Generated by Django 4.1.3 on 2022-12-01 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Music', '0007_alter_collaborative_music_rating_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collaborative_music',
            name='rating',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='collaborative_music',
            name='song_id',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='collaborative_music',
            name='user_id',
            field=models.BigIntegerField(),
        ),
    ]
