# Generated by Django 4.1.3 on 2022-12-01 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Music', '0008_alter_collaborative_music_rating_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contentbase_Music',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist_name', models.CharField(max_length=200)),
                ('track_name', models.CharField(max_length=200)),
                ('genre', models.CharField(max_length=200)),
                ('topic', models.CharField(max_length=200)),
                ('concat', models.CharField(max_length=200)),
            ],
        ),
    ]
